### PR TITLE
Generalized mapping update to support new features properly.

### PR DESCRIPTION
**Pull request by belyaev-andrey**
Refactored EclipseLinkSessionEventListener class, removed hardcoded mapping updates.

Introduced new interfaces:
MappingProcessor - that updates entity mappings to support various CUBA features like UUID support, EmbeddedAttributes support, Soft delete support

JoinExpressionProvider - part of the previous update, allows generating join criteria to make mapping update more flexible. In the CUBA core, it generates join expression to support soft delete, but we can use it for multi-tenancy.

### CODE REVIEW

**Comment by knstvk** [comment]
I think `processors` sub-package is unnecessary, `com.haulmont.cuba.core.sys.persistence.mapping` would be enough. Moreover, `JoinExpressionProvider` is also in this package.

**Comment by belyaev-andrey** [comment]
> I think `processors` sub-package is unnecessary, `com.haulmont.cuba.core.sys.persistence.mapping` would be enough. Moreover, `JoinExpressionProvider` is also in this package.

Looks OK to me, will update if needed

**Comment by knstvk** [comment]
> Looks OK to me, will update if needed

Update plz

**Comment by belyaev-andrey** [comment]
Done.

**Pull request merged**
