### PR TITLE
Add multiLineCells parameter to table presentation settings

### PR DESCRIPTION
**Pull request by daring2**
Implement the feature discribed in the issue #2956

### CODE REVIEW

**Comment by Flaurite** [comment]
Hello @daring2,

thank you for the pull request! But, unfortunately, it is not a thing that should be done. Most likely, it is not a user choice to use this property. 'multiLineCells' is a design-time attribute that does not imply changes at runtime.
Enable/disable this property at runtime is not reliable as it seems at first glance because the table can contain complicated UI (editable, generated columns, etc) that can be broken.

**Comment by daring2** [comment]
> Enable/disable this property at runtime is not reliable as it seems at first glance...

I didn't think about it. We received a request about this feature from our users. From the user perspective it is just a presentation option like colums visibility, size, etc

Thank you for your answer.

**Comment by Flaurite** [comment]
If it is really need to implement, you can write your own settings in the screen. See:
```
Screen#saveSettings();

Screen#applySettings(Settings);
```
Also, you can extend Table component and make this property working at runtime or override settings logic. See this forum thread how to do it: [link](https://www.cuba-platform.com/discuss/t/how-is-the-way-to-extends-components-like-button/12276/3). Probably, in this case there is no need to create another interface for component, so in the _ui-component.xsd_ you can write the original name of Table:
```
    <component>
        <name>table</name>
        <class>com.company.example.web.mytable.WebExtTable</class>
    </component>
```

**Comment by daring2** [comment]
> If it is really need to implement, you can write your own settings in the screen...

Yes, we already implemented it this way, it works properly. I had thought this feature is general and convinient for users so I created this PR.

 Thank you for the adivse!

**Pull request closed without merging**
