### PR TITLE
If two queries have the same fields, they should be equals

### PR DESCRIPTION
**Pull request by ikuchmin**

### CODE REVIEW

**Comment by AdamSkywalker** [comment]
what is the motivation?

**Comment by ikuchmin** [comment]
I think that two queries will be equals if they satisfy some rules. If you want to check two instances by references, you should use operator `==`

**Comment by knstvk** [comment]
Have you ever had the need to check equality of LoadContext.Query?

**Comment by ikuchmin** [comment]
Of course. When we apply presentation (with sort by some column) for the table. If we execute `applyPresentation` from a callback CollectionDatasource, sort by column will not be applied. Since `ds::refresh` by sort will be executed during `ds::refresh` by callback. After that table has incorrect view, data isn't sorted. We override method `refresh` in ds:
```
    /**
     * Refresh datasource when query was changed during previous refresh
     *
     * @param parameters parameters
     */
    default void refreshMixin(Map<String, Object> parameters) {

        if (cubaGetInRefresh().get()) return;

        try {
            cubaSetInRefresh().accept(true);

            cubaRefresh().accept(parameters);

            Query lastQuery = cubaGetLastQuery().get();
            if (lastQuery != null) {
                // It is possible when query was changed during previous refresh.
                // For example, table can be resort when ds is updated
                LoadContext newContext = cubaBeforeLoadData().apply(parameters);
                if (!equalsQueries(newContext.getQuery(), lastQuery)) {
                    cubaRefresh().accept(parameters);
                }
            }
        } finally {
            cubaSetInRefresh().accept(false);
        }
    }
```

**Comment by jreznot** [comment]
Thank you! Merged, see: https://youtrack.cuba-platform.com/issue/PL-8661

**Pull request closed without merging**
