### PR TITLE
FileStorageAPI was migrated to global module and parametrized

### PR DESCRIPTION
**Pull request by ikuchmin**
FileStorageAPI was migrated to global module. It was parametrized with parameter T. Other code was migrated to use FileStorageAPI with parameter

### CODE REVIEW

**Comment by jreznot** [comment]
Why we should move FileStorageAPI to the global module ? It is the internal part of core server. Client should not know about it.

**Comment by ikuchmin** [comment]
Comment from chat. -> I found that FileStorageAPI is placed in core module. It is strange, because i want to use it in module which hasn’t dependency on core, for example web. Likewise, i think that FileStorageAPI should be parametrised with T.

**Comment by jreznot** [comment]
If you want to use FileStorage - you have to use FileStorageService and FileDataProvidee. We definitely don't want to move internal API of middleware to global.

**Comment by jreznot** [comment]
If course in case of client. In midleware you can use FileStorageAPI as is.

**Comment by ikuchmin** [comment]
What is a reason to have two implementations of storage API (FileStorageService, FileStorageAPI)?

**Comment by jreznot** [comment]
And what about parametrization? Why do we need it?

**Comment by jreznot** [comment]
Clients uses FileStorageService because now it is the only way to separate client and middleware in cluster deployment. How does your API work in cluster?

**Comment by ikuchmin** [comment]
If i make CustomFileDescriptor as child of FileDescriptor, i will want to have interface where methods have arguments as CustomFileDescriptor. It is necessary because my implementation of store can be depended of custom fields in CustomFileDescriptor. Of course, i can check that argument is my custom FileDescriptor and throw exception in other cases.

**Comment by jreznot** [comment]
Won't fix

**Pull request closed without merging**
