### PR TITLE
Update Composition.java

### PR DESCRIPTION
**Pull request by kgeis**
fix typo

### CODE REVIEW

**Comment by knstvk** [comment]
Please accept the CLA

**Comment by kgeis** [comment]
I don't think I can sign your CLA. I work for a public research university. Some of my contribution to CUBA could be on my employer's time; given the extense of its intellectual property, the university is strongly against CLAs with broad patent clauses. Please consider adding a trivial change exception to your contribution model.

**Comment by jreznot** [comment]
In this case we just close it and will fix it later or someone for community can contribute a fix

**Comment by kgeis** [comment]
It's kind of absurd that you can't accept my contribution without me signing a CLA but then you don't worry about me asserting intellectual property rights if someone else "steals" that typo fix from me. Just saying...

**Comment by glaschenko** [comment]
Hello Ken,
I agree this is a weird situation. We will consider how we can handle such cases in the CLA going forward. For now unfortunately we cannot accept requests without CLA.

**Pull request closed without merging**
